Traceback (most recent call last):
  File "/home/dkeathley/anaconda3/lib/python3.8/site-packages/jupyter_cache/executors/utils.py", line 51, in single_nb_execution
    executenb(
  File "/home/dkeathley/anaconda3/lib/python3.8/site-packages/nbclient/client.py", line 1204, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
  File "/home/dkeathley/anaconda3/lib/python3.8/site-packages/nbclient/util.py", line 84, in wrapped
    return just_run(coro(*args, **kwargs))
  File "/home/dkeathley/anaconda3/lib/python3.8/site-packages/nbclient/util.py", line 62, in just_run
    return loop.run_until_complete(coro)
  File "/home/dkeathley/anaconda3/lib/python3.8/asyncio/base_events.py", line 616, in run_until_complete
    return future.result()
  File "/home/dkeathley/anaconda3/lib/python3.8/site-packages/nbclient/client.py", line 663, in async_execute
    await self.async_execute_cell(
  File "/home/dkeathley/anaconda3/lib/python3.8/site-packages/nbclient/client.py", line 965, in async_execute_cell
    await self._check_raise_for_error(cell, cell_index, exec_reply)
  File "/home/dkeathley/anaconda3/lib/python3.8/site-packages/nbclient/client.py", line 862, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
# Estimate the probability of getting more than k photons
import scipy
from scipy.stats import poisson

k = 1 # default is 1: how often does Alice send > 1 photon?
mu = 0.5 # set the mean value (the above text uses lambda instead of mu)
prob = gt(k,mu)

def gt(k,mu):
    xx = 1-poisson.cdf(k=kk, mu=mu)
    return xx
print(f"The probability of getting more than {k} photons with mean {mu} is {prob}")

------------------

[0;31m---------------------------------------------------------------------------[0m
[0;31mNameError[0m                                 Traceback (most recent call last)
[0;32m/tmp/ipykernel_930530/338321062.py[0m in [0;36m<cell line: 7>[0;34m()[0m
[1;32m      5[0m [0mk[0m [0;34m=[0m [0;36m1[0m [0;31m# default is 1: how often does Alice send > 1 photon?[0m[0;34m[0m[0;34m[0m[0m
[1;32m      6[0m [0mmu[0m [0;34m=[0m [0;36m0.5[0m [0;31m# set the mean value (the above text uses lambda instead of mu)[0m[0;34m[0m[0;34m[0m[0m
[0;32m----> 7[0;31m [0mprob[0m [0;34m=[0m [0mgt[0m[0;34m([0m[0mk[0m[0;34m,[0m[0mmu[0m[0;34m)[0m[0;34m[0m[0;34m[0m[0m
[0m[1;32m      8[0m [0;34m[0m[0m
[1;32m      9[0m [0;32mdef[0m [0mgt[0m[0;34m([0m[0mk[0m[0;34m,[0m[0mmu[0m[0;34m)[0m[0;34m:[0m[0;34m[0m[0;34m[0m[0m

[0;31mNameError[0m: name 'gt' is not defined
NameError: name 'gt' is not defined

